config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #list of all the list of tasks 
  get 'tasks', to: 'tasks#index'
  
  # As a user, I can add a new task 
  # One route is there to display the Task form, and 
  get "tasks/new", to: "tasks#new"
  #another one is there to handle the POST request generated when submitting this form.
  post "tasks", to: "tasks#create"
  
  #view the details of a task: localhost/3000/tasks/1
  get "tasks/:id", to: "tasks#show", as: :task
  # As a user, I can edit a task
  # GET the HTML form (pre-filled with restaurant attributes) for editing = 1 request
  get "tasks/:id/edit", to: "tasks#edit", as: :task_edit
  # PATCH the parameters to update an existing restaurant = 1 request
  patch "tasks/:id", to: "tasks#update"
 
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task <  ApplicationRecord
    
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ActionController::Base
    before_action :set_task, only: [:show, :edit, :update, :destroy]

def index
    @tasks = Task.all
end

def show
   end

  def new
    @task = Task.new # needed to instantiate the form_for
  end

  def create
    @task= Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to tasks_path
  end

 def edit
 end

 def update
    @task.update(task_params)
        # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
 end

 def destroy
    @task .destroy
    # no need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end

  def set_task
    @task = Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit a task </h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
    <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>List of all tasks to do </h1>
<ul>
<% @tasks.each do |task| %>
 <li><%= link_to task.title, task %></li>
 <% end %>
 </ul>
<%= link_to  "Add a  new task", tasks_new_path%>

app/views/tasks/new.html.erb
<h1>Add a new task </h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
  
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>


<%= link_to  "Edit a task", task_edit_path(@task) %>

<%= link_to "Delete task",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>